kanban/kanbanize/urls.py
from django.conf.urls import patterns, include, url
from kanban.views import UserLogin, UserRegister, CreateUserStoryCard, BoardsList, DisplayBoard, Users, AddUser, \
    EditUser, CreateBoard, CreateColumn, Help, EditCard, AverageLeadTime, CumulativeFlowDiagram, WipList, TaskDistributionDiagram
from kanban.create_database import PopulateDatabase, PopulateDatabaseTeamBoard, PopulateCardMovements
from datetime import datetime
from apscheduler.scheduler import Scheduler
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
import kanban.utilities
from django.views.generic import TemplateView
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'kanban.views.home', name='home'),

    #user authentication
    url(r'^accounts/login/$', UserLogin.as_view(), name='login'),
    url(r'^accounts/register/', UserRegister.as_view(), name='register'),
    url(r'^accounts/logout', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),

    #user maintance
    url(r'^users/$', Users.as_view(), name='users'),
    url(r'^users/add_user$', AddUser.as_view(), name='add_user'),
    url(r'^users/edit_user/(?P<user_id>\d+)/', EditUser.as_view(), name='edit_user'),
    url(r'^accounts/register/', UserRegister.as_view(), name='register'),
    url(r'^accounts/logout', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),

    #documentation
    url(r'^help/$', Help.as_view(), name='help'),

    #development teams maintenance
    #url(r'^teams/add_team/$', 'teams.views.add_team', name='add_team'),
    #url(r'^teams/add_team/find_members$', 'teams.views.find_members', name='find_members'),
    #url(r'^teams/add_team/find_members/(?P<user_id>[0-9]+)$', 'teams.views.add_member', name='add_member'),
    #url(r'^teams/add_team/remove_member/(?P<user_id>[0-9]+)$', 'teams.views.remove_member', name='remove_member'),


    #creating and updating teams
    url(r'^teams/$', 'kanban.views.team', name='team'),
    url(r'^teams/create_team/$', 'kanban.views.create_team', name='create_team'),
    url(r'^teams/(?P<team_id>[0-9]+)$', 'kanban.views.show_team', name='show_team'),
    url(r'^teams/(?P<team_id>[0-9]+)/update_team/$', 'kanban.views.update_team', name='update_team'),
    url(r'^teams/activity/$', 'kanban.views.team_activity', name='activity'),
    #url(r'^teams/create_team/roles$', 'teams.views.assign_roles'),

    #creating and updating projects
    url(r'^projects/$', 'kanban.views.project', name='project'),
    url(r'^projects/create_project/$', 'kanban.views.create_project', name='create_project'),
    url(r'^projects/(?P<project_id>[0-9]+)/edit_project/$', 'kanban.views.edit_project', name='edit_project'),
    url(r'^projects/(?P<project_id>[0-9]+)/deactivate/$', 'kanban.views.deactivate_project', name='deactivate_project'),
    url(r'^projects/(?P<project_id>[0-9]+)/activate/$', 'kanban.views.activate_project', name='activate_project'),


    #user story cards
    url(r'^boards/display_board/(?P<board_id>\d+)/create_card/(?P<card_type>\w+)$', CreateUserStoryCard.as_view(), name='create_card'),
    url(r'^boards/display_board/(?P<board_id>\d+)/create_card/violation/$',
        'kanban.views.confirm_wip_violation_and_create_card', name='confirm_wip_violation_and_create_card'),
    url(r'^boards/display_board/edit_card/(?P<card_id>\d+)$', EditCard.as_view(), name='edit_card'),
    url(r'^boards/display_board/(?P<board_id>\d+)/move_card/(?P<card_id>\d+)/(?P<direction>\w+)$', 'kanban.views.move_card', name='confirm_wip_violation_and_create_card'),
    url(r'^boards/display_board/(?P<board_id>\d+)/move_card/(?P<card_id>\d+)/(?P<direction>\w+)$', 'kanban.views.move_card', name='move_card'),
    url(r'^boards/display_board/(?P<board_id>\d+)/move_card/violation/(?P<card_id>\d+)/(?P<subcolumn_id>\d+)$', 'kanban.views.confirm_wip_violation', name='confirm_wip_violation'),
    url(r'^boards/display_board/(?P<board_id>\d+)/decline_story/(?P<card_id>\d+)$', 'kanban.views.decline_story', name='decline_story'),
    url(r'^boards/display_board/(?P<board_id>\d+)/card_movement_permission/$', 'kanban.views.card_movement_permission', name='card_movement_permission'),
    url(r'^boards/display_board/(?P<board_id>\d+)/card_movement_permission/add/$', 'kanban.views.add_card_movement_permission', name='add_card_movement_permission'),
    url(r'^boards/display_board/(?P<board_id>\d+)/card_movement_permission/(?P<card_movement_permission_id>\d+)/edit/$', 'kanban.views.edit_card_movement_permission', name='edit_card_movement_permission'),
    url(r'^boards/display_board/(?P<board_id>\d+)/card_movement_permission/(?P<card_movement_permission_id>\d+)/remove/$', 'kanban.views.remove_card_movement_permission', name='remove_card_movement_permission'),
    url(r'^cards/(?P<card_id>\d+)/card_details/$', 'kanban.views.card_details', name='card_details'),
    url(r'^cards/(?P<card_id>\d+)/delete_card/$', 'kanban.views.delete_card', name='delete_card'),
    url(r'^cards/(?P<card_id>\d+)/add_task/$', 'kanban.views.add_task', name='add_task'),
    url(r'^cards/(?P<card_id>\d+)/edit_task/(?P<task_id>\d+)/$', 'kanban.views.edit_task', name='edit_task'),
    url(r'^cards/(?P<card_id>\d+)/delete_task/(?P<task_id>\d+)/(?P<to_redir>\d+)/$', 'kanban.views.delete_task', name='delete_task'),

    # Boards.
    url(r'^boards/$', BoardsList.as_view(), name='boards'),
    url(r'^boards/display_board/(?P<board_id>\d+)$', DisplayBoard.as_view(), name='display_board'),
    url(r'^boards/display_board/(?P<board_id>\d+)/properties$', 'kanban.views.board_properties', name='board_properties'),
    url(r'^boards/create_board/$', CreateBoard.as_view(), name='create_board'),
    url(r'^boards/copy_board_structure/(?P<board_id>\d+)$', 'kanban.views.copy_board_structure', name='copy_board_structure'),
    url(r'^boards/create_column/(?P<board_id>\d+)/(?P<order>\d+)$', CreateColumn.as_view(), name='create_column'),
    url(r'^boards/update_column/(?P<column_id>\d+)$', 'kanban.views.update_column', name='update_column'),
    url(r'^boards/update_column/violation/(?P<column_id>\d+)/(?P<new_name>[\w ]+)/(?P<new_wip_limit>\d+)$', 'kanban.views.update_column_violation', name='update_column_violation'),
    url(r'^boards/collapse_column/(?P<column_id>\d+)$', 'kanban.views.collapse_column', name='collapse_column'),
    url(r'^boards/delete_column/(?P<column_id>\d+)$', 'kanban.views.delete_column', name='delete_column'),
    url(r'^boards/create_swim_lane/(?P<board_id>\d+)$', 'kanban.views.create_swim_lane', name='create_swim_lane'),
    url(r'^boards/delete_swim_lanes/(?P<board_id>\d+)$', 'kanban.views.delete_swim_lanes', name='delete_swim_lanes'),
    url(r'^boards/delete_swim_lane/(?P<swim_lane_id>\d+)$', 'kanban.views.delete_swim_lane', name='delete_swim_lane'),
    url(r'^boards/create_subcolumn/(?P<column_id>\d+)/(?P<order>\d+)$', 'kanban.views.create_subcolumn', name='create_subcolumn'),
    url(r'^boards/update_subcolumn/(?P<subcolumn_id>\d+)$', 'kanban.views.update_subcolumn', name='update_subcolumn'),
    url(r'^boards/delete_subcolumn/(?P<subcolumn_id>\d+)$', 'kanban.views.delete_subcolumn', name='delete_subcolumn'),

    #WIP violations
    url(r'^wip_list/(?P<board_id>\d+)$', WipList.as_view(), name='wip_list'),

    #Average lead time
    url(r'^boards/average_lead_time/(?P<board_id>\d+)$', AverageLeadTime.as_view(), name='average_lead_time'),

    # Cumulative flow diagram
    url(r'^boards/cumulative_flow_diagram/(?P<board_id>\d+)$', CumulativeFlowDiagram.as_view(),
        name='cumulative_flow_diagram'),

    #Task distribution diagram
    url(r'^boards/task_distribution_diagram/(?P<board_id>\d+)$', TaskDistributionDiagram.as_view(),
        name='task_distribution_diagram'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # Populate database
    url(r'^populate_database$', PopulateDatabase.as_view(), name='populate_database'),
    url(r'^populate_database_team_board$', PopulateDatabaseTeamBoard.as_view(), name='populate_database_teams_board'),
    url(r'^populate_card_movements$', PopulateCardMovements.as_view(), name='populate_card_movements')

)

# This is here because urls.py execute once and once only.

sched = Scheduler()
sched.start()

sched.add_cron_job(kanban.utilities.send_mail_reminder, day_of_week='mon-sun', hour=0, minute=5)

kanban/teams/models.py
from django.db import models

# Create your models here.

kanban/teams/forms.py
__author__ = 'Pavilion'

#Forms for maintaining development team

from django import forms
from django.db import models
from django.core.exceptions import ValidationError
from kanban.models import Team
from django.contrib.auth.models import User
import copy


USERS = ((user.id, user.first_name+" "+user.last_name+"-"+user.username) for user in User.objects.all())


def team_name_taken(name):
    if Team.objects.filter(team_name=name):
        raise ValidationError('Team name already taken')

def get_users(users_id):
    all_users = [User.objects.get(pk=id) for id in users_id]
    return ((user.id, user.first_name+" "+user.last_name+"-"+user.username) for user in all_users)





"""




#Form for creating new team
class AddTeamForm(forms.Form):
    team_name = forms.CharField(max_length=100, validators=[team_name_taken])




class AddTeamMember(forms.Form):
    member = forms.CharField(max_length=100)

"""

class CreateTeamForm(forms.Form):
    team_name = forms.CharField(max_length=100, validators=[team_name_taken])
    members = forms.MultipleChoiceField(choices=USERS)


class AssignRoles(forms.Form):

    def __init__(self, *args, **kwargs):
        self.team_members_id = kwargs.pop('team_members_id')
        super(AssignRoles, self).__init__(*args, **kwargs)

        self.fields['product_owner'] = forms.ChoiceField(choices=get_users(self.team_members_id))
        self.fields['kanban_master'] = forms.ChoiceField(choices=get_users(self.team_members_id))
        self.fields['developers'] = forms.MultipleChoiceField(choices=get_users(self.team_members_id))


    def clean(self):
        cleaned_data = super(AssignRoles, self).clean()
        product_owner = cleaned_data.get('product_owner')
        kanban_master = cleaned_data.get('kanban_master')
        developers = cleaned_data.get('developers')

        if not developers:
            #raise ValidationError("Have to pick at least one developer!")
            pass
        else:
            team_members = self.team_members_id

            if product_owner in team_members:
                team_members.remove(product_owner)

            if kanban_master in team_members:
                team_members.remove(kanban_master)

            for developer in developers:
                if developer in team_members:
                    team_members.remove(developer)

            if team_members:
                raise ValidationError("Not all members have role assigned!")

        return self.cleaned_data

kanban/templates/teams/activity.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_content %}
    <li><a href="{% url 'logout' %}">Log out</a></li>
{% endblock %}

{% block content %}

{% include "left_navigation.html" %}
<div id="content">
    <div class="container">
        <div class="page-header" id="banner">
            <div class="row from_top">
                <h3>Your activities in teams</h3>
                <br/>
                {% for team, activities in all_teams_activities %}
                    <h4>Team: {{ team.team_name }}</h4>
                    <ol>
                        {% for activity in activities %}
                            <li>{{ activity.active_from }} {% if activity.active_until %} - {{ activity.active_until }} {% endif %}</li>
                         {% endfor %}
                    </ol>
                    <br/>
                {% endfor %}

            </div>
        </div>
    </div>
</div>
{% endblock %}

kanban/templates/teams/add_team.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_content %}
    <li><a href="{% url 'logout' %}">Log out</a></li>
{% endblock %}

{% block content %}
<div class="container">
    <div class="page-header" id="banner">
        <div class="row from_top">
            Tukaj je bo prostor za dodajanje novih skupin
        </div>
    </div>
</div>
{% endblock %}

kanban/templates/teams/create_team.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_content %}
    <li><a href="{% url 'logout' %}">Log out</a></li>
{% endblock %}

{% block content %}

{% include "left_navigation.html" %}
<div id="content">
    <div class="container">
        <div class="page-header" id="banner">
            <div class="row from_top">

                {% if permission_error %}
                    <p> {{ permission_error }}</p>

                {% else %}

                    {% if create_team_form %}

                        <form action="" method="post" style="width: 400px">
                        <h4 class="form-signin-heading">Please create your team</h4>
                            <br/>
                            {% csrf_token %}

                                {{ create_team_form.non_field_errors }}


                                {% for error in create_team_form.team_name.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_team_name">Team name</label>
                                <p>{{ create_team_form.team_name }}</p>
                                <br/>
                                {% for error in create_team_form.product_owner.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_product_owner">Product owner</label>
                                <p>{{ create_team_form.product_owner }}</p>
                                <br/>
                                {% for error in create_team_form.kanba_master.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_kanban_master">Kanban master</label>
                                <p>{{ create_team_form.kanban_master }}</p>
                                <br/>
                                {% for error in create_team_form.developers.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_developers">Developers</label>
                                <p>{{ create_team_form.developers }}</p>


                            <button class="btn btn-primary" type="submit">Create Team</button>
                        </form>

                    {% else %}
                        <h4 class="form-signin-heading">Team successfully created!</h4>

                    {% endif %}

                {% endif %}

            </div>
        </div>
    </div>
</div>
{% endblock %}









    {% comment %}
     <!--Display form for creating new team -->
            {% if form %}
                <p>DODAJ NOVO EKIPO</p>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Submit" />
                </form>

            <!--Name of the team has been chosen - add users to the team-->
            {% elif submitted %}
                <form action="{% url 'find_members' %}" method="post">
                    {% csrf_token %}
                    {{ add_member_form.as_p }}
                    <input type="submit" value="Submit" />
                </form>
                <br />
                {% if users %}
                    {% for user in users %}

                        <p>{{ user.first_name }} {{ user.last_name }} - {{ user.username }} <a href="/teams/add_team/find_members/{{ user.id }}">Dodaj</a></p>
                    {% endfor %}
                {% elif error %}
                    <p> {{ error }}</p>
                {% endif %}

                <p>Dosedaj dodani uporabniki</p>
                {% for user in users_added %}

                    <p>{{ user.first_name }} {{ user.last_name }} <a href="/teams/add_team/remove_member/{{ user.id }}">Odstrani</a></p>
                {% endfor %}



            {% endif %}

            {% if create_team_form %}
                <p>DODAJ NOVO EKIPO</p>
                <form action="" method="post">
                      {% csrf_token %}
                      {{ create_team_form.as_p }}
                <input type="submit" value="Submit" />
                </form>

            {% elif ok %}
                <p>Team name: {{ team_name }}</p>

                {% comment %}

                <form action="roles" method="post">
                        {% csrf_token %}
                        <p>Select product owner
                        <select name="product_owner">
                        {% for member in team_members %}
                            <option value="{{ member.id }}">{{ member.first_name }} {{ member.last_name }}</option>
                        {% endfor %}
                        </select>
                        </p>

                        <br/>

                        <p>Select kanban master
                        <select name="kanban_master">
                        {% for member in team_members %}
                            <option value="{{ member.id }}">{{ member.first_name }} {{ member.last_name }}</option>
                        {% endfor %}
                        </select>
                        </p>

                        <br/>

                        <p>Select team developers:
                        {% if no_developers_error %}
                            {{ no_developers_error }}
                        {% endif %}

                        <table width="300px">
                        {% for member in team_members %}
                            <tr>
                                <td>{{ member.first_name }} {{ member.last_name }}</td>
                                <td><input type="checkbox" name="developers" value="{{ member.id }}"> {{ role.role_name }}</td>
                            </tr>
                        {% endfor %}
                        </table>
                        </p>

                    <input type="submit" value="Submit" />
                </form>



                <form action="roles" method="post">
                    {% csrf_token %}
                    {{ assign_role_form.as_p }}
                    <input type="submit" value="Submit" />
                </form>



            {% endif %}


            {% if message %}
                {{ message }}
            {% endif %}


                {% for t in tmi %}
                {{ t }}
                {% endfor %}
            {% endcomment %}

kanban/templates/teams/show_team.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_content %}
    <li><a href="{% url 'logout' %}">Log out</a></li>
{% endblock %}

{% block content %}

{% include "left_navigation.html" %}
<div id="content">
    <div class="container">
        <div class="page-header" id="banner">
            <div class="row from_top">
                <h4>Team name: </h4>
                <p>{{ team.team_name }}</p>

                <br/>

                <h4>Product owner:</h4>
                <p>{{ po.user.first_name }} {{ po.user.last_name }} ({{ po.user.username }})</p>

                <br/>

                <h4> Kanban master: </h4>
                <p>{{ kbm.user.first_name }} {{ kbm.user.last_name }} ({{ kbm.user.username }})</p>

                <br/>

                <h4> Developers: </h4>
                {% for developer in developers %}
                    <p> {{ developer.user.first_name }} {{ developer.user.last_name }} -  {{ developer.user.username }} </p>
                {% endfor %}

                <br/>

                {% if request.user.userprofile.id == kbm.id %}
                    <a href="{% url 'update_team' team.id %}"> Update </a>
                {% endif %}

            </div>
        </div>
    </div>
</div>
{% endblock %}

kanban/templates/teams/team.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_content %}
    <li><a href="{% url 'logout' %}">Log out</a></li>
{% endblock %}

{% block content %}

{% include "left_navigation.html" %}
<div id="content">
    <div class="container">
        <div class="page-header" id="banner">
            <div class="row from_top">
                {% if teams|length > 0 %}
                    <h3>Your teams</h3>
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>Team</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for team in teams %}
                                <tr>
                                    <td>{{ team.team_name }} <a href="{% url 'show_team' team.id %}" style="float:right"> Show </a></td>
                                </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <h3>You do not have any team. {% if request.user.userprofile.can_be_kbm %} Create your first. {% endif %}</h3>
                {% endif %}
                {% if request.user.userprofile.can_be_kbm %}
                    <a href="{% url 'create_team' %}"><button type="button" class="btn btn-primary">Create team</button></a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

kanban/templates/teams/update_team.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_content %}
    <li><a href="{% url 'logout' %}">Log out</a></li>
{% endblock %}

{% block content %}

{% include "left_navigation.html" %}
<div id="content">
    <div class="container">
        <div class="page-header" id="banner">
            <div class="row from_top">

                {% if permission_error %}

                    <p> {{ permission_error }} </p>

                {% elif update_team_form %}

                    <form action="" method="post" style="width: 400px">
                    <h4 class="form-signin-heading">Please update your team ({{ team.team_name }})</h4>
                        <br/>
                        {% csrf_token %}

                            {% if update_team_form.non_field_errors %}
                            {% for error in update_team_form.non_field_errors %}
                                <p style="color: red; font-weight: bold">{{ error }}</p>
                            {% endfor %}
                            <br/>
                            {% endif %}

                            {% for error in update_team_form.product_owner.errors %}
                                <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                            {% endfor %}
                            <label for="id_product_owner">New product owner (if no change, leave)</label>
                            <p>{{ update_team_form.product_owner }}</p>
                            <br/>
                            {% for error in update_team_form.kanban_master.errors %}
                                <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                            {% endfor %}
                            <label for="id_kanban_master">New kanban master (if no change, leave)</label>
                            <p>{{ update_team_form.kanban_master }}</p>
                            <br/>
                            {% for error in update_team_form.add_developers.errors %}
                                <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                            {% endfor %}
                            <label for="id_add_developers">New developers</label>
                            <p>{{ update_team_form.add_developers }}</p>
                            <br/>
                            {% for error in update_team_formremove_developers.errors %}
                                <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                            {% endfor %}
                            <label for="id_remove_developers">Remove developers</label>
                            <p>{{ update_team_form.remove_developers }}</p>


                        <button class="btn btn-primary" type="submit">Update Team</button>
                    </form>

                {% else %}

                    <h4 class="form-signin-heading">Team successfully updated!</h4>

                {% endif %}

            </div>
        </div>
    </div>
</div>
{% endblock %}