kanban/kanbanize/urls.py
from django.conf.urls import patterns, include, url
from kanban.views import UserLogin, UserRegister, CreateUserStoryCard, BoardsList, DisplayBoard, Users, AddUser, \
    EditUser, CreateBoard, CreateColumn, Help, EditCard, AverageLeadTime, CumulativeFlowDiagram, WipList, TaskDistributionDiagram
from kanban.create_database import PopulateDatabase, PopulateDatabaseTeamBoard, PopulateCardMovements
from datetime import datetime
from apscheduler.scheduler import Scheduler
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
import kanban.utilities
from django.views.generic import TemplateView
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'kanban.views.home', name='home'),

    #user authentication
    url(r'^accounts/login/$', UserLogin.as_view(), name='login'),
    url(r'^accounts/register/', UserRegister.as_view(), name='register'),
    url(r'^accounts/logout', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),

    #user maintance
    url(r'^users/$', Users.as_view(), name='users'),
    url(r'^users/add_user$', AddUser.as_view(), name='add_user'),
    url(r'^users/edit_user/(?P<user_id>\d+)/', EditUser.as_view(), name='edit_user'),
    url(r'^accounts/register/', UserRegister.as_view(), name='register'),
    url(r'^accounts/logout', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),

    #documentation
    url(r'^help/$', Help.as_view(), name='help'),

    #development teams maintenance
    #url(r'^teams/add_team/$', 'teams.views.add_team', name='add_team'),
    #url(r'^teams/add_team/find_members$', 'teams.views.find_members', name='find_members'),
    #url(r'^teams/add_team/find_members/(?P<user_id>[0-9]+)$', 'teams.views.add_member', name='add_member'),
    #url(r'^teams/add_team/remove_member/(?P<user_id>[0-9]+)$', 'teams.views.remove_member', name='remove_member'),


    #creating and updating teams
    url(r'^teams/$', 'kanban.views.team', name='team'),
    url(r'^teams/create_team/$', 'kanban.views.create_team', name='create_team'),
    url(r'^teams/(?P<team_id>[0-9]+)$', 'kanban.views.show_team', name='show_team'),
    url(r'^teams/(?P<team_id>[0-9]+)/update_team/$', 'kanban.views.update_team', name='update_team'),
    url(r'^teams/activity/$', 'kanban.views.team_activity', name='activity'),
    #url(r'^teams/create_team/roles$', 'teams.views.assign_roles'),

    #creating and updating projects
    url(r'^projects/$', 'kanban.views.project', name='project'),
    url(r'^projects/create_project/$', 'kanban.views.create_project', name='create_project'),
    url(r'^projects/(?P<project_id>[0-9]+)/edit_project/$', 'kanban.views.edit_project', name='edit_project'),
    url(r'^projects/(?P<project_id>[0-9]+)/deactivate/$', 'kanban.views.deactivate_project', name='deactivate_project'),
    url(r'^projects/(?P<project_id>[0-9]+)/activate/$', 'kanban.views.activate_project', name='activate_project'),


    #user story cards
    url(r'^boards/display_board/(?P<board_id>\d+)/create_card/(?P<card_type>\w+)$', CreateUserStoryCard.as_view(), name='create_card'),
    url(r'^boards/display_board/(?P<board_id>\d+)/create_card/violation/$',
        'kanban.views.confirm_wip_violation_and_create_card', name='confirm_wip_violation_and_create_card'),
    url(r'^boards/display_board/edit_card/(?P<card_id>\d+)$', EditCard.as_view(), name='edit_card'),
    url(r'^boards/display_board/(?P<board_id>\d+)/move_card/(?P<card_id>\d+)/(?P<direction>\w+)$', 'kanban.views.move_card', name='confirm_wip_violation_and_create_card'),
    url(r'^boards/display_board/(?P<board_id>\d+)/move_card/(?P<card_id>\d+)/(?P<direction>\w+)$', 'kanban.views.move_card', name='move_card'),
    url(r'^boards/display_board/(?P<board_id>\d+)/move_card/violation/(?P<card_id>\d+)/(?P<subcolumn_id>\d+)$', 'kanban.views.confirm_wip_violation', name='confirm_wip_violation'),
    url(r'^boards/display_board/(?P<board_id>\d+)/decline_story/(?P<card_id>\d+)$', 'kanban.views.decline_story', name='decline_story'),
    url(r'^boards/display_board/(?P<board_id>\d+)/card_movement_permission/$', 'kanban.views.card_movement_permission', name='card_movement_permission'),
    url(r'^boards/display_board/(?P<board_id>\d+)/card_movement_permission/add/$', 'kanban.views.add_card_movement_permission', name='add_card_movement_permission'),
    url(r'^boards/display_board/(?P<board_id>\d+)/card_movement_permission/(?P<card_movement_permission_id>\d+)/edit/$', 'kanban.views.edit_card_movement_permission', name='edit_card_movement_permission'),
    url(r'^boards/display_board/(?P<board_id>\d+)/card_movement_permission/(?P<card_movement_permission_id>\d+)/remove/$', 'kanban.views.remove_card_movement_permission', name='remove_card_movement_permission'),
    url(r'^cards/(?P<card_id>\d+)/card_details/$', 'kanban.views.card_details', name='card_details'),
    url(r'^cards/(?P<card_id>\d+)/delete_card/$', 'kanban.views.delete_card', name='delete_card'),
    url(r'^cards/(?P<card_id>\d+)/add_task/$', 'kanban.views.add_task', name='add_task'),
    url(r'^cards/(?P<card_id>\d+)/edit_task/(?P<task_id>\d+)/$', 'kanban.views.edit_task', name='edit_task'),
    url(r'^cards/(?P<card_id>\d+)/delete_task/(?P<task_id>\d+)/(?P<to_redir>\d+)/$', 'kanban.views.delete_task', name='delete_task'),

    # Boards.
    url(r'^boards/$', BoardsList.as_view(), name='boards'),
    url(r'^boards/display_board/(?P<board_id>\d+)$', DisplayBoard.as_view(), name='display_board'),
    url(r'^boards/display_board/(?P<board_id>\d+)/properties$', 'kanban.views.board_properties', name='board_properties'),
    url(r'^boards/create_board/$', CreateBoard.as_view(), name='create_board'),
    url(r'^boards/copy_board_structure/(?P<board_id>\d+)$', 'kanban.views.copy_board_structure', name='copy_board_structure'),
    url(r'^boards/create_column/(?P<board_id>\d+)/(?P<order>\d+)$', CreateColumn.as_view(), name='create_column'),
    url(r'^boards/update_column/(?P<column_id>\d+)$', 'kanban.views.update_column', name='update_column'),
    url(r'^boards/update_column/violation/(?P<column_id>\d+)/(?P<new_name>[\w ]+)/(?P<new_wip_limit>\d+)$', 'kanban.views.update_column_violation', name='update_column_violation'),
    url(r'^boards/collapse_column/(?P<column_id>\d+)$', 'kanban.views.collapse_column', name='collapse_column'),
    url(r'^boards/delete_column/(?P<column_id>\d+)$', 'kanban.views.delete_column', name='delete_column'),
    url(r'^boards/create_swim_lane/(?P<board_id>\d+)$', 'kanban.views.create_swim_lane', name='create_swim_lane'),
    url(r'^boards/delete_swim_lanes/(?P<board_id>\d+)$', 'kanban.views.delete_swim_lanes', name='delete_swim_lanes'),
    url(r'^boards/delete_swim_lane/(?P<swim_lane_id>\d+)$', 'kanban.views.delete_swim_lane', name='delete_swim_lane'),
    url(r'^boards/create_subcolumn/(?P<column_id>\d+)/(?P<order>\d+)$', 'kanban.views.create_subcolumn', name='create_subcolumn'),
    url(r'^boards/update_subcolumn/(?P<subcolumn_id>\d+)$', 'kanban.views.update_subcolumn', name='update_subcolumn'),
    url(r'^boards/delete_subcolumn/(?P<subcolumn_id>\d+)$', 'kanban.views.delete_subcolumn', name='delete_subcolumn'),

    #WIP violations
    url(r'^wip_list/(?P<board_id>\d+)$', WipList.as_view(), name='wip_list'),

    #Average lead time
    url(r'^boards/average_lead_time/(?P<board_id>\d+)$', AverageLeadTime.as_view(), name='average_lead_time'),

    # Cumulative flow diagram
    url(r'^boards/cumulative_flow_diagram/(?P<board_id>\d+)$', CumulativeFlowDiagram.as_view(),
        name='cumulative_flow_diagram'),

    #Task distribution diagram
    url(r'^boards/task_distribution_diagram/(?P<board_id>\d+)$', TaskDistributionDiagram.as_view(),
        name='task_distribution_diagram'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # Populate database
    url(r'^populate_database$', PopulateDatabase.as_view(), name='populate_database'),
    url(r'^populate_database_team_board$', PopulateDatabaseTeamBoard.as_view(), name='populate_database_teams_board'),
    url(r'^populate_card_movements$', PopulateCardMovements.as_view(), name='populate_card_movements')

)

# This is here because urls.py execute once and once only.

sched = Scheduler()
sched.start()

sched.add_cron_job(kanban.utilities.send_mail_reminder, day_of_week='mon-sun', hour=0, minute=5)

kanban/kanban/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime

# Create your models here.

#
# USER RELATED MODELS
#

#Extended user - add fields if your app needs them
class UserProfile(models.Model):
    user = models.OneToOneField(User)
    can_be_kbm = models.BooleanField()
    can_be_po = models.BooleanField()
    can_be_dp = models.BooleanField()

    class Meta:
        db_table = 'user_profile'

    def __unicode__(self):
        return self.user.username

#Model, which represents team - many to many relation to User
class Team(models.Model):
    team_name = models.CharField(max_length=200)
    members = models.ManyToManyField(UserProfile, through='MemberTeam')

    class Meta:
        db_table = 'team'

    def __unicode__(self):
        return self.team_name

#Model containing information about particular user being member in particular team
class MemberTeam(models.Model):
    id = models.AutoField(primary_key=True)
    member = models.ForeignKey(UserProfile)
    team = models.ForeignKey(Team)
    is_active = models.BooleanField()
    date_added = models.DateTimeField(default=timezone.now())

    class Meta:
        db_table = 'member_team'

    def __str__(self):
        return self.member.user.username +" " +self.team.team_name

#Model which contains all the possible roles available - they are KanbanMaster, ProductOwner, Developer
class Role(models.Model):
    id = models.AutoField(primary_key=True)
    role_name = models.CharField(max_length=100)
    member_team_roles = models.ManyToManyField(MemberTeam, through='MemberTeamRole')

    class Meta:
        db_table = 'role'

    def __str__(self):
        return self.role_name

#Model which contains roles of particular member in particular team
class MemberTeamRole(models.Model):
    id = models.AutoField(primary_key=True)
    member_team = models.ForeignKey(MemberTeam)
    role = models.ForeignKey(Role)

    class Meta:
        db_table = 'member_team_role'

    def __str__(self):
        return "Team: " +self.member_team.team.team_name +" role: " +self.role.role_name

#Model which contains information about period of activity of particular member in particular team - member was active from active_from until active_until(can be null, member stil active)
class MemberTeamActivity(models.Model):
    id = models.AutoField(primary_key=True)
    member_team = models.ForeignKey(MemberTeam)
    active_from = models.DateTimeField('active_from', default=timezone.now())
    active_until = models.DateTimeField('active_until', blank=True, null=True)

    class Meta:
        db_table = 'member_team_activity'

#
# BOARD RELATED MODELS
#

class Board(models.Model):
    name = models.CharField(max_length=200)
    should_display_priority = models.BooleanField(default=False)
    should_display_points = models.BooleanField(default=False)
    should_display_date_to_finish = models.BooleanField(default=False)
    n_days_reminder = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'board'

class Column(models.Model):
    board = models.ForeignKey(Board)
    order = models.IntegerField()
    name = models.CharField(max_length=200)
    wip_limit = models.PositiveIntegerField(null=True, blank=True)
    collapsed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'column'

class Subcolumn(models.Model):
    column = models.ForeignKey(Column)
    order = models.IntegerField()
    name = models.CharField(max_length=200, null=False, blank=False, default="Default Subcolumn")
    is_border_column = models.BooleanField(default=False)
    is_highest_priority_card_column = models.BooleanField(default=False)
    is_acceptance_testing_column = models.BooleanField(default=False)

    def __str__(self):
        return self.column.name + ": " + self.name

    class Meta:
        db_table = 'subcolumn'
        ordering = ['order']

"""
class Project(models.Model):
    code = models.CharField(max_length=50)
    title = models.CharField(max_length=100)
    client_name = models.CharField(max_length=100)
    start_date = models.DateField()
    anticipated_end_date = models.DateField()
    team = models.ForeignKey(Team, null=True) # Remove null after some teams are created in create_database.

    class Meta:
        db_table = 'project'
"""

class Project(models.Model):
    code = models.CharField(max_length=50)
    title = models.CharField(max_length=100)
    client_name = models.CharField(max_length=100)
    start_date = models.DateField()
    anticipated_end_date = models.DateField()
    finished_date = models.DateField(blank=True, null=True)
    team = models.ForeignKey(Team)
    is_active = models.BooleanField(default=True)
    work_started = models.BooleanField(default=False)

    class Meta:
        db_table = 'project'

    def __str__(self):
        return self.title


class SwimLane(models.Model):
    project = models.OneToOneField(Project, related_name='swim_lane')
    board = models.ForeignKey(Board)
    order = models.IntegerField(null=False, blank=False)

    class Meta:
        db_table = 'swim_lane'

#
# CARD RELATED MODELS
#

CARD_TYPES = (
    ('nc', 'Normal card'),
    ('sb', 'Silver bullet'),
    ('rc', 'Rejected card')
)

CARD_PRIORITIES = {
    ('low', 'Low'),
    ('med', 'Medium'),
    ('high', 'High')
}


#Model for a card that represents one user story.
class UserStoryCard(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=1000)
    subcolumn = models.ForeignKey(Subcolumn)
    project = models.ForeignKey(Project)
    type = models.CharField(max_length=100, choices=CARD_TYPES)
    priority = models.CharField(max_length=100, choices=CARD_PRIORITIES)
    points = models.DecimalField(decimal_places=2, max_digits=5)
    date_created = models.DateTimeField(default=datetime.datetime.today())
    development_started = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)
    deletion_reason = models.CharField(max_length=200, null=True)
    responsible_person = models.ForeignKey(UserProfile, null=True)
    date_to_finish = models.DateField(null=True)

    class Meta:
        db_table = 'user_story_card'

    def __unicode__(self):
        return self.title




#
# WIP violation RELATED MODELS
#

#Model for work in progress (WIP) violations
WIP_REASONS = (
    ('cm', 'Card movement'),
    ('cc', 'Card creation'),
)
class WIPViolation(models.Model):
    card = models.ForeignKey(UserStoryCard)
    date = models.DateField()
    column = models.ForeignKey(Column)
    user = models.ForeignKey(User)
    reason = models.CharField(max_length=100, choices=WIP_REASONS)

    class Meta:
        db_table = 'wip_violation'

    def __unicode__(self):
        return self.card.title +", " +str(self.date) +" violation."


class WIPColumnViolation(models.Model):
    column = models.ForeignKey(Column)
    date = models.DateField()
    user = models.ForeignKey(User)

    class Meta:
        db_table = 'wip_column_violation'

    def __unicode__(self):
        return self.column.name + ", "+ self.date + " column WIP violation."
    
class CardMovement(models.Model):
    card = models.ForeignKey(UserStoryCard)
    column_from = models.ForeignKey(Column, related_name='column_from')
    column_to = models.ForeignKey(Column, related_name='column_to')
    user = models.ForeignKey(User)
    date = models.DateTimeField(default=datetime.datetime.today())

    class Meta:
        db_table = 'card_movement'

    def __str__(self):
        return self.card.title + 'from ' + self.column_from.name + ' to ' + self.column_to.name

class CardMovementPermission(models.Model):
    subcolumn_from = models.ForeignKey(Subcolumn, related_name='subcolumn_from')
    subcolumn_to = models.ForeignKey(Subcolumn, related_name='subcolumn_to')
    po_allowed = models.BooleanField(default=True)
    kbm_allowed = models.BooleanField(default=True)
    dp_allowed = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'card_movement_permission'


class VisualSettings(models.Model):
    font_size_const = models.IntegerField()

    class Meta:
        db_table = 'visual_settings'


class Task(models.Model):
    description = models.CharField(max_length=1000)
    hours = models.PositiveIntegerField()
    completed = models.BooleanField(default=False)
    card = models.ForeignKey(UserStoryCard)

    class Meta:
        db_table = 'task'

kanban/templates/projects/create_project.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_content %}
    <li><a href="{% url 'logout' %}">Log out</a></li>
{% endblock %}

{% block content %}

{% include "left_navigation.html" %}
<div id="content">
    <div class="container">
        <div class="page-header" id="banner">
            <div class="row from_top">



                {% if permission_error %}
                    <p> {{ permission_error }}</p>

                {% else %}

                    {% if create_project_form %}

                        <form action="" method="post" style="width: 400px">
                        <h4 class="form-signin-heading">Please create your project</h4>
                            <br/>
                            {% csrf_token %}



                                {{ create_project_form.non_field_errors }}


                                {% for error in create_project_form.code.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_code">Project code</label>
                                <p>{{ create_project_form.code }}</p>
                                <br/>
                                {% for error in create_project_form.title.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_title">Project title</label>
                                <p>{{ create_project_form.title }}</p>
                                <br/>
                                {% for error in create_project_form.client_name.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_clinet_name">Client name</label>
                                <p>{{ create_project_form.client_name }}</p>
                                <br/>
                                {% for error in create_project_form.start_date.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_start_date">Start date</label>
                                <p>{{ create_project_form.start_date }}</p>
                                <br/>
                                {% for error in create_project_form.anticipated_end_date.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_anticipated_and_date">Anticipated end date</label>
                                <p>{{ create_project_form.anticipated_end_date }}</p>
                                <br/>
                                {% for error in create_project_form.team.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_team">Team</label>
                                <p>{{ create_project_form.team }}</p>
                                <br/>


                                <script>
                                    $('#id_start_date').datepicker({
                                        format: 'yyyy-mm-dd',
                                        endDate: '+0d',
                                        autoclose: true
                                    });
                                    $('#id_anticipated_end_date').datepicker({
                                        format: 'yyyy-mm-dd',
                                        autoclose: true
                                    });
                                </script>


                            <button class="btn btn-primary" type="submit">Create Project</button>
                        </form>

                {% else %}
                    <h4 class="form-signin-heading">Project has been successfully created!</h4>

                {% endif %}

            {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

kanban/templates/projects/edit_project.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_content %}
    <li><a href="{% url 'logout' %}">Log out</a></li>
{% endblock %}

{% block content %}

{% include "left_navigation.html" %}
<div id="content">
    <div class="container">
        <div class="page-header" id="banner">
            <div class="row from_top">

                {% if permission_error %}
                    <p> {{ permission_error }}</p>

                {% else %}

                    {% if edit_project_form %}

                        <form action="" method="post" style="width: 400px">
                        <h4 class="form-signin-heading">Please edit your project</h4>
                            <br/>
                            {% csrf_token %}



                                {{ edit_project_form.non_field_errors }}


                                {% for error in edit_project_form.code.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_code">Project code</label>
                                <p>{{ edit_project_form.code }}</p>
                                <br/>
                                {% for error in edit_project_form.title.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_title">Project title</label>
                                <p>{{ edit_project_form.title }}</p>
                                <br/>
                                {% for error in edit_project_form.client_name.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_client_name">Client name</label>
                                <p>{{ edit_project_form.client_name }}</p>
                                <br/>
                                {% for error in edit_project_form.start_date.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_start_date">Start date</label>
                                <p>{{ edit_project_form.start_date }}</p>
                                <br/>
                                {% for error in edit_project_form.anticipated_end_date.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_anticipated_end_date">Anticipated end date</label>
                                <p>{{ edit_project_form.anticipated_end_date }}</p>
                                <br/>
                                 {% for error in edit_project_form.finished_date.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_finished_date">Finished date</label>
                                <p>{{ edit_project_form.finished_date }}</p>
                                <br/>
                                {% for error in edit_project_form.team.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_team">Team</label>
                                <p>{{ edit_project_form.team }}</p>
                                <br/>


                                <script>
                                    {% if not project.work_started %}
                                    $('#id_start_date').datepicker({
                                        format: 'yyyy-mm-dd',
                                        endDate: '+0d',
                                        autoclose: true
                                    });
                                    {% endif %}
                                    $('#id_anticipated_end_date').datepicker({
                                        format: 'yyyy-mm-dd',
                                        autoclose: true
                                    });
                                    $('#id_finished_date').datepicker({
                                        format: 'yyyy-mm-dd',
                                        startDate: '+1d',
                                        autoclose: true
                                    });
                                </script>



                            <button class="btn btn-primary" type="submit">Edit Project</button>
                        </form>

                {% else %}
                    <h4 class="form-signin-heading">Project has been successfully edited!</h4>

                {% endif %}

            {% endif %}

            </div>
        </div>
    </div>
</div>
{% endblock %}

kanban/templates/projects/project.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_content %}
    <li><a href="{% url 'logout' %}">Log out</a></li>
{% endblock %}

{% block content %}

{% include "left_navigation.html" %}
<div id="content">
    <div class="container">
        <div class="page-header" id="banner">
            <div class="row from_top">
                {% if projects|length > 0 %}
                    <h3>Your projects</h3>

                    {% if deactivation_error %}
                         <p style="color: red; font-weight: bold">{{ deactivation_error }}</p>
                    {% endif %}

                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>Code</th>
                            <th>Title</th>
                            <th>Client name</th>
                            <th>Team</th>
                            <th>Active</th>
                            <th>Work started</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for project, team_kbm in projects %}
                                <tr>
                                    <td> {{ project.code }} </td>
                                    <td> {{ project.title }} </td>
                                    <td> {{ project.client_name }} </td>
                                    <td> {{ project.team.team_name }} </td>
                                    <td> {% if project.is_active %} Yes {% else %} No {% endif %}</td>
                                    <td> {% if project.work_started %} Yes {% else %} No {% endif %}</td>
                                    <td>
                                        {% if request.user.userprofile.id == team_kbm.id %}
                                            <a href="{% url 'edit_project' project.id %}"> <span class="glyphicon glyphicon-edit"> Edit </span></a>
                                            {% if project.is_active %}
                                                <a href="{% url 'deactivate_project' project.id %}"> <span class="glyphicon glyphicon-remove-circle"> Deactivate </span></a>
                                            {% else %}
                                                <a href="{% url 'activate_project' project.id %}"> <span class="glyphicon glyphicon-ok-circle"> Activate </span></a>
                                            {% endif %}
                                        {% endif %}
                                    </td>
                                </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <h3>You do not have any projects. {% if request.user.userprofile.can_be_kbm %} Create your first. {% endif %}</h3>
                {% endif %}
                {% if request.user.userprofile.can_be_kbm %}
                    <a href="{% url 'create_project' %}"><button type="button" class="btn btn-primary">Create project</button></a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}