kanban/kanbanize/urls.py
from django.conf.urls import patterns, include, url
from kanban.views import UserLogin, UserRegister, CreateUserStoryCard, BoardsList, DisplayBoard, Users, AddUser, \
    EditUser, CreateBoard, CreateColumn, Help, EditCard, AverageLeadTime, CumulativeFlowDiagram, WipList, TaskDistributionDiagram
from kanban.create_database import PopulateDatabase, PopulateDatabaseTeamBoard, PopulateCardMovements
from datetime import datetime
from apscheduler.scheduler import Scheduler
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
import kanban.utilities
from django.views.generic import TemplateView
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'kanban.views.home', name='home'),

    #user authentication
    url(r'^accounts/login/$', UserLogin.as_view(), name='login'),
    url(r'^accounts/register/', UserRegister.as_view(), name='register'),
    url(r'^accounts/logout', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),

    #user maintance
    url(r'^users/$', Users.as_view(), name='users'),
    url(r'^users/add_user$', AddUser.as_view(), name='add_user'),
    url(r'^users/edit_user/(?P<user_id>\d+)/', EditUser.as_view(), name='edit_user'),
    url(r'^accounts/register/', UserRegister.as_view(), name='register'),
    url(r'^accounts/logout', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),

    #documentation
    url(r'^help/$', Help.as_view(), name='help'),

    #development teams maintenance
    #url(r'^teams/add_team/$', 'teams.views.add_team', name='add_team'),
    #url(r'^teams/add_team/find_members$', 'teams.views.find_members', name='find_members'),
    #url(r'^teams/add_team/find_members/(?P<user_id>[0-9]+)$', 'teams.views.add_member', name='add_member'),
    #url(r'^teams/add_team/remove_member/(?P<user_id>[0-9]+)$', 'teams.views.remove_member', name='remove_member'),


    #creating and updating teams
    url(r'^teams/$', 'kanban.views.team', name='team'),
    url(r'^teams/create_team/$', 'kanban.views.create_team', name='create_team'),
    url(r'^teams/(?P<team_id>[0-9]+)$', 'kanban.views.show_team', name='show_team'),
    url(r'^teams/(?P<team_id>[0-9]+)/update_team/$', 'kanban.views.update_team', name='update_team'),
    url(r'^teams/activity/$', 'kanban.views.team_activity', name='activity'),
    #url(r'^teams/create_team/roles$', 'teams.views.assign_roles'),

    #creating and updating projects
    url(r'^projects/$', 'kanban.views.project', name='project'),
    url(r'^projects/create_project/$', 'kanban.views.create_project', name='create_project'),
    url(r'^projects/(?P<project_id>[0-9]+)/edit_project/$', 'kanban.views.edit_project', name='edit_project'),
    url(r'^projects/(?P<project_id>[0-9]+)/deactivate/$', 'kanban.views.deactivate_project', name='deactivate_project'),
    url(r'^projects/(?P<project_id>[0-9]+)/activate/$', 'kanban.views.activate_project', name='activate_project'),


    #user story cards
    url(r'^boards/display_board/(?P<board_id>\d+)/create_card/(?P<card_type>\w+)$', CreateUserStoryCard.as_view(), name='create_card'),
    url(r'^boards/display_board/(?P<board_id>\d+)/create_card/violation/$',
        'kanban.views.confirm_wip_violation_and_create_card', name='confirm_wip_violation_and_create_card'),
    url(r'^boards/display_board/edit_card/(?P<card_id>\d+)$', EditCard.as_view(), name='edit_card'),
    url(r'^boards/display_board/(?P<board_id>\d+)/move_card/(?P<card_id>\d+)/(?P<direction>\w+)$', 'kanban.views.move_card', name='confirm_wip_violation_and_create_card'),
    url(r'^boards/display_board/(?P<board_id>\d+)/move_card/(?P<card_id>\d+)/(?P<direction>\w+)$', 'kanban.views.move_card', name='move_card'),
    url(r'^boards/display_board/(?P<board_id>\d+)/move_card/violation/(?P<card_id>\d+)/(?P<subcolumn_id>\d+)$', 'kanban.views.confirm_wip_violation', name='confirm_wip_violation'),
    url(r'^boards/display_board/(?P<board_id>\d+)/decline_story/(?P<card_id>\d+)$', 'kanban.views.decline_story', name='decline_story'),
    url(r'^boards/display_board/(?P<board_id>\d+)/card_movement_permission/$', 'kanban.views.card_movement_permission', name='card_movement_permission'),
    url(r'^boards/display_board/(?P<board_id>\d+)/card_movement_permission/add/$', 'kanban.views.add_card_movement_permission', name='add_card_movement_permission'),
    url(r'^boards/display_board/(?P<board_id>\d+)/card_movement_permission/(?P<card_movement_permission_id>\d+)/edit/$', 'kanban.views.edit_card_movement_permission', name='edit_card_movement_permission'),
    url(r'^boards/display_board/(?P<board_id>\d+)/card_movement_permission/(?P<card_movement_permission_id>\d+)/remove/$', 'kanban.views.remove_card_movement_permission', name='remove_card_movement_permission'),
    url(r'^cards/(?P<card_id>\d+)/card_details/$', 'kanban.views.card_details', name='card_details'),
    url(r'^cards/(?P<card_id>\d+)/delete_card/$', 'kanban.views.delete_card', name='delete_card'),
    url(r'^cards/(?P<card_id>\d+)/add_task/$', 'kanban.views.add_task', name='add_task'),
    url(r'^cards/(?P<card_id>\d+)/edit_task/(?P<task_id>\d+)/$', 'kanban.views.edit_task', name='edit_task'),
    url(r'^cards/(?P<card_id>\d+)/delete_task/(?P<task_id>\d+)/(?P<to_redir>\d+)/$', 'kanban.views.delete_task', name='delete_task'),

    # Boards.
    url(r'^boards/$', BoardsList.as_view(), name='boards'),
    url(r'^boards/display_board/(?P<board_id>\d+)$', DisplayBoard.as_view(), name='display_board'),
    url(r'^boards/display_board/(?P<board_id>\d+)/properties$', 'kanban.views.board_properties', name='board_properties'),
    url(r'^boards/create_board/$', CreateBoard.as_view(), name='create_board'),
    url(r'^boards/copy_board_structure/(?P<board_id>\d+)$', 'kanban.views.copy_board_structure', name='copy_board_structure'),
    url(r'^boards/create_column/(?P<board_id>\d+)/(?P<order>\d+)$', CreateColumn.as_view(), name='create_column'),
    url(r'^boards/update_column/(?P<column_id>\d+)$', 'kanban.views.update_column', name='update_column'),
    url(r'^boards/update_column/violation/(?P<column_id>\d+)/(?P<new_name>[\w ]+)/(?P<new_wip_limit>\d+)$', 'kanban.views.update_column_violation', name='update_column_violation'),
    url(r'^boards/collapse_column/(?P<column_id>\d+)$', 'kanban.views.collapse_column', name='collapse_column'),
    url(r'^boards/delete_column/(?P<column_id>\d+)$', 'kanban.views.delete_column', name='delete_column'),
    url(r'^boards/create_swim_lane/(?P<board_id>\d+)$', 'kanban.views.create_swim_lane', name='create_swim_lane'),
    url(r'^boards/delete_swim_lanes/(?P<board_id>\d+)$', 'kanban.views.delete_swim_lanes', name='delete_swim_lanes'),
    url(r'^boards/delete_swim_lane/(?P<swim_lane_id>\d+)$', 'kanban.views.delete_swim_lane', name='delete_swim_lane'),
    url(r'^boards/create_subcolumn/(?P<column_id>\d+)/(?P<order>\d+)$', 'kanban.views.create_subcolumn', name='create_subcolumn'),
    url(r'^boards/update_subcolumn/(?P<subcolumn_id>\d+)$', 'kanban.views.update_subcolumn', name='update_subcolumn'),
    url(r'^boards/delete_subcolumn/(?P<subcolumn_id>\d+)$', 'kanban.views.delete_subcolumn', name='delete_subcolumn'),

    #WIP violations
    url(r'^wip_list/(?P<board_id>\d+)$', WipList.as_view(), name='wip_list'),

    #Average lead time
    url(r'^boards/average_lead_time/(?P<board_id>\d+)$', AverageLeadTime.as_view(), name='average_lead_time'),

    # Cumulative flow diagram
    url(r'^boards/cumulative_flow_diagram/(?P<board_id>\d+)$', CumulativeFlowDiagram.as_view(),
        name='cumulative_flow_diagram'),

    #Task distribution diagram
    url(r'^boards/task_distribution_diagram/(?P<board_id>\d+)$', TaskDistributionDiagram.as_view(),
        name='task_distribution_diagram'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # Populate database
    url(r'^populate_database$', PopulateDatabase.as_view(), name='populate_database'),
    url(r'^populate_database_team_board$', PopulateDatabaseTeamBoard.as_view(), name='populate_database_teams_board'),
    url(r'^populate_card_movements$', PopulateCardMovements.as_view(), name='populate_card_movements')

)

# This is here because urls.py execute once and once only.

sched = Scheduler()
sched.start()

sched.add_cron_job(kanban.utilities.send_mail_reminder, day_of_week='mon-sun', hour=0, minute=5)

kanban/kanban/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime

# Create your models here.

#
# USER RELATED MODELS
#

#Extended user - add fields if your app needs them
class UserProfile(models.Model):
    user = models.OneToOneField(User)
    can_be_kbm = models.BooleanField()
    can_be_po = models.BooleanField()
    can_be_dp = models.BooleanField()

    class Meta:
        db_table = 'user_profile'

    def __unicode__(self):
        return self.user.username

#Model, which represents team - many to many relation to User
class Team(models.Model):
    team_name = models.CharField(max_length=200)
    members = models.ManyToManyField(UserProfile, through='MemberTeam')

    class Meta:
        db_table = 'team'

    def __unicode__(self):
        return self.team_name

#Model containing information about particular user being member in particular team
class MemberTeam(models.Model):
    id = models.AutoField(primary_key=True)
    member = models.ForeignKey(UserProfile)
    team = models.ForeignKey(Team)
    is_active = models.BooleanField()
    date_added = models.DateTimeField(default=timezone.now())

    class Meta:
        db_table = 'member_team'

    def __str__(self):
        return self.member.user.username +" " +self.team.team_name

#Model which contains all the possible roles available - they are KanbanMaster, ProductOwner, Developer
class Role(models.Model):
    id = models.AutoField(primary_key=True)
    role_name = models.CharField(max_length=100)
    member_team_roles = models.ManyToManyField(MemberTeam, through='MemberTeamRole')

    class Meta:
        db_table = 'role'

    def __str__(self):
        return self.role_name

#Model which contains roles of particular member in particular team
class MemberTeamRole(models.Model):
    id = models.AutoField(primary_key=True)
    member_team = models.ForeignKey(MemberTeam)
    role = models.ForeignKey(Role)

    class Meta:
        db_table = 'member_team_role'

    def __str__(self):
        return "Team: " +self.member_team.team.team_name +" role: " +self.role.role_name

#Model which contains information about period of activity of particular member in particular team - member was active from active_from until active_until(can be null, member stil active)
class MemberTeamActivity(models.Model):
    id = models.AutoField(primary_key=True)
    member_team = models.ForeignKey(MemberTeam)
    active_from = models.DateTimeField('active_from', default=timezone.now())
    active_until = models.DateTimeField('active_until', blank=True, null=True)

    class Meta:
        db_table = 'member_team_activity'

#
# BOARD RELATED MODELS
#

class Board(models.Model):
    name = models.CharField(max_length=200)
    should_display_priority = models.BooleanField(default=False)
    should_display_points = models.BooleanField(default=False)
    should_display_date_to_finish = models.BooleanField(default=False)
    n_days_reminder = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'board'

class Column(models.Model):
    board = models.ForeignKey(Board)
    order = models.IntegerField()
    name = models.CharField(max_length=200)
    wip_limit = models.PositiveIntegerField(null=True, blank=True)
    collapsed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'column'

class Subcolumn(models.Model):
    column = models.ForeignKey(Column)
    order = models.IntegerField()
    name = models.CharField(max_length=200, null=False, blank=False, default="Default Subcolumn")
    is_border_column = models.BooleanField(default=False)
    is_highest_priority_card_column = models.BooleanField(default=False)
    is_acceptance_testing_column = models.BooleanField(default=False)

    def __str__(self):
        return self.column.name + ": " + self.name

    class Meta:
        db_table = 'subcolumn'
        ordering = ['order']

"""
class Project(models.Model):
    code = models.CharField(max_length=50)
    title = models.CharField(max_length=100)
    client_name = models.CharField(max_length=100)
    start_date = models.DateField()
    anticipated_end_date = models.DateField()
    team = models.ForeignKey(Team, null=True) # Remove null after some teams are created in create_database.

    class Meta:
        db_table = 'project'
"""

class Project(models.Model):
    code = models.CharField(max_length=50)
    title = models.CharField(max_length=100)
    client_name = models.CharField(max_length=100)
    start_date = models.DateField()
    anticipated_end_date = models.DateField()
    finished_date = models.DateField(blank=True, null=True)
    team = models.ForeignKey(Team)
    is_active = models.BooleanField(default=True)
    work_started = models.BooleanField(default=False)

    class Meta:
        db_table = 'project'

    def __str__(self):
        return self.title


class SwimLane(models.Model):
    project = models.OneToOneField(Project, related_name='swim_lane')
    board = models.ForeignKey(Board)
    order = models.IntegerField(null=False, blank=False)

    class Meta:
        db_table = 'swim_lane'

#
# CARD RELATED MODELS
#

CARD_TYPES = (
    ('nc', 'Normal card'),
    ('sb', 'Silver bullet'),
    ('rc', 'Rejected card')
)

CARD_PRIORITIES = {
    ('low', 'Low'),
    ('med', 'Medium'),
    ('high', 'High')
}


#Model for a card that represents one user story.
class UserStoryCard(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=1000)
    subcolumn = models.ForeignKey(Subcolumn)
    project = models.ForeignKey(Project)
    type = models.CharField(max_length=100, choices=CARD_TYPES)
    priority = models.CharField(max_length=100, choices=CARD_PRIORITIES)
    points = models.DecimalField(decimal_places=2, max_digits=5)
    date_created = models.DateTimeField(default=datetime.datetime.today())
    development_started = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)
    deletion_reason = models.CharField(max_length=200, null=True)
    responsible_person = models.ForeignKey(UserProfile, null=True)
    date_to_finish = models.DateField(null=True)

    class Meta:
        db_table = 'user_story_card'

    def __unicode__(self):
        return self.title




#
# WIP violation RELATED MODELS
#

#Model for work in progress (WIP) violations
WIP_REASONS = (
    ('cm', 'Card movement'),
    ('cc', 'Card creation'),
)
class WIPViolation(models.Model):
    card = models.ForeignKey(UserStoryCard)
    date = models.DateField()
    column = models.ForeignKey(Column)
    user = models.ForeignKey(User)
    reason = models.CharField(max_length=100, choices=WIP_REASONS)

    class Meta:
        db_table = 'wip_violation'

    def __unicode__(self):
        return self.card.title +", " +str(self.date) +" violation."


class WIPColumnViolation(models.Model):
    column = models.ForeignKey(Column)
    date = models.DateField()
    user = models.ForeignKey(User)

    class Meta:
        db_table = 'wip_column_violation'

    def __unicode__(self):
        return self.column.name + ", "+ self.date + " column WIP violation."
    
class CardMovement(models.Model):
    card = models.ForeignKey(UserStoryCard)
    column_from = models.ForeignKey(Column, related_name='column_from')
    column_to = models.ForeignKey(Column, related_name='column_to')
    user = models.ForeignKey(User)
    date = models.DateTimeField(default=datetime.datetime.today())

    class Meta:
        db_table = 'card_movement'

    def __str__(self):
        return self.card.title + 'from ' + self.column_from.name + ' to ' + self.column_to.name

class CardMovementPermission(models.Model):
    subcolumn_from = models.ForeignKey(Subcolumn, related_name='subcolumn_from')
    subcolumn_to = models.ForeignKey(Subcolumn, related_name='subcolumn_to')
    po_allowed = models.BooleanField(default=True)
    kbm_allowed = models.BooleanField(default=True)
    dp_allowed = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'card_movement_permission'


class VisualSettings(models.Model):
    font_size_const = models.IntegerField()

    class Meta:
        db_table = 'visual_settings'


class Task(models.Model):
    description = models.CharField(max_length=1000)
    hours = models.PositiveIntegerField()
    completed = models.BooleanField(default=False)
    card = models.ForeignKey(UserStoryCard)

    class Meta:
        db_table = 'task'

kanban/templates/boards/board_properties.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_content %}
    <li><a href="{% url 'logout' %}">Log out</a></li>
{% endblock %}

{% block content %}

    {% include "left_navigation.html" %}
    <div id="content">
        <div class="container">
            <div class="page-header" id="banner">
                <div class="row from_top">

                    {% if permission_error %}
                        <p> {{ permission_error }}</p>

                    {% else %}

                        {% if board_properties_form %}

                            <form action="" method="post" style="width: 400px">
                                <h4 class="form-signin-heading">Cards settings</h4>
                                <br/>
                                {% csrf_token %}

                                {{ board_properties_form.non_field_errors }}

                                {% for error in board_properties_form.name.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_name">Should display priority?</label>
                                <p>{{ board_properties_form.should_display_priority }}</p>
                                <br />
                                <label for="id_name">Should display points?</label>
                                <p>{{ board_properties_form.should_display_points }}</p>
                                <br />
                                <label for="id_name">Should display date to finish?</label>
                                <p>{{ board_properties_form.should_display_date_to_finish }}</p>
                                <br />
                                <label for="id_name">Number of days reminder prior card is finished:</label>
                                <p>{{ board_properties_form.n_days_reminder }}</p>
                                <br />

                                <button class="btn btn-primary" type="submit">Update cards settings</button>
                            </form>


                        {% else %}
                            <h4 class="form-signin-heading">Cards settings successfully updated!</h4>

                        {% endif %}

                    {% endif %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}

kanban/templates/boards/create_column.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_content %}
    <li><a href="{% url 'logout' %}">Log out</a></li>
{% endblock %}

{% block content %}

    {% include "left_navigation.html" %}
    <div id="content">
        <div class="container">
            <div class="page-header" id="banner">
                <div class="row from_top">

                    {% if permission_error %}
                        <p> {{ permission_error }}</p>

                    {% else %}

                        {% if create_column_form %}

                            <form action="" method="post" style="width: 400px">
                                <h4 class="form-signin-heading">Create a column</h4>
                                <br/>
                                {% csrf_token %}

                                {{ create_column_form.non_field_errors }}

                                {% for error in create_column_form.name.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_name">Column name</label>
                                <p>{{ create_column_form.name }}</p>
                                <br />
                                {% for error in create_column_form.wip_limit.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_name">WIP limit</label>
                                <p>{{ create_column_form.wip_limit }}</p>
                                <br />
                                <label for="id_name">Is this column a border column?</label>
                                <p>{{ create_column_form.is_border_column }}</p>
                                <br />
                                <label for="id_name">Is this column a highest priority card column?</label>
                                <p>{{ create_column_form.is_highest_priority_card_column }}</p>
                                <br />
                                <label for="id_name">Is this column acceptance testing column?</label>
                                <p>{{ create_column_form.is_acceptance_testing_column }}</p>
                                <br />


                                <button class="btn btn-primary" type="submit">Create a column</button>
                            </form>

                        {% else %}
                            <h4 class="form-signin-heading">Column successfully created!</h4>

                        {% endif %}

                    {% endif %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}

kanban/templates/boards/create_swim_lane.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_content %}
    <li><a href="{% url 'logout' %}">Log out</a></li>
{% endblock %}

{% block content %}

    {% include "left_navigation.html" %}
    <div id="content">
        <div class="container">
            <div class="page-header" id="banner">
                <div class="row from_top">

                    {% if permission_error %}
                        <p> {{ permission_error }}</p>

                    {% else %}

                        {% if create_swim_lane_form %}

                            <form action="" method="post" style="width: 400px">
                                <h4 class="form-signin-heading">Create a Swim Lane</h4>
                                <br/>
                                {% csrf_token %}

                                {{ create_swim_lane_form.non_field_errors }}

                                {% for error in create_swim_lane_form.name.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_name">Project</label>
                                <p>{{ create_swim_lane_form.project }}</p>
                                <br />

                                <button class="btn btn-primary" type="submit">Create Swim Lane</button>
                            </form>


                        {% else %}
                            <h4 class="form-signin-heading">Swim lane successfully created!</h4>

                        {% endif %}

                    {% endif %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}

kanban/templates/boards/update_column.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_content %}
    <li><a href="{% url 'logout' %}">Log out</a></li>
{% endblock %}

{% block content %}

    {% include "left_navigation.html" %}
    <div id="content">
        <div class="container">
            <div class="page-header" id="banner">
                <div class="row from_top">

                    {% if permission_error %}
                        <p> {{ permission_error }}</p>

                    {% else %}

                        {% if violation %}
                            <h4> WIP violation detected. Please confirm your action. </h4>
                            <a href="{% url 'kanban.views.update_column_violation' column_id new_name new_wip_limit %}"><button type="button" class="btn btn-primary">Confirm</button> </a>
                        {% elif update_column_form %}

                            <form action="" method="post" style="width: 400px">
                                <h4 class="form-signin-heading">Update a column</h4>
                                <br/>
                                {% csrf_token %}

                                {{ update_column_form.non_field_errors }}

                                {% for error in update_column_form.name.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_name">Column name</label>
                                <p>{{ update_column_form.name }}</p>
                                <br />
                                {% for error in update_column_form.wip_limit.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_wip_limit">WIP limit</label>
                                <p>{{ update_column_form.wip_limit }}</p>
                                <br />

                                <button class="btn btn-primary" type="submit">Update a column</button>
                            </form>

                            <br />

                            <a href="{% url 'delete_column' column_id %}" class="btn btn-danger btn-large">
                                <i class="icon-white icon-remove"></i> Delete this column
                            </a>

                            <br /><br /><br />
                            <h3> WIP Violations </h3>

                            {% if column_wip_violations|length > 0 %}

                                <table class="table table-hover">
                                    <thead>
                                    <tr>
                                        <th>User</th>
                                        <th>Date</th>
                                    </tr>
                                    </thead>

                                    {% for column_wip_violation in column_wip_violations %}
                                        <tr>
                                            <td> {{ column_wip_violation.column.name }} </td>
                                            <td> {{ column_wip_violation.user.username }} </td>
                                            <td> {{ column_wip_violation.date }} </td>
                                        </tr>
                                    {% endfor %}


                                </table>

                            {% else %}
                                <h4> There are no WIP violations made on this column. </h4>
                            {% endif %}

                        {% else %}
                            <h4 class="form-signin-heading">Column successfully updated!</h4>

                        {% endif %}

                    {% endif %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}

kanban/templates/boards/update_subcolumn.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_content %}
    <li><a href="{% url 'logout' %}">Log out</a></li>
{% endblock %}

{% block content %}

    {% include "left_navigation.html" %}
    <div id="content">
        <div class="container">
            <div class="page-header" id="banner">
                <div class="row from_top">

                    {% if permission_error %}
                        <p> {{ permission_error }}</p>

                    {% else %}

                        {% if update_subcolumn_form %}

                            <form action="" method="post" style="width: 400px">
                                <h4 class="form-signin-heading">Update a subcolumn</h4>
                                <br/>
                                {% csrf_token %}

                                {{ update_subcolumn_form.non_field_errors }}

                                {% for error in update_subcolumn_form.name.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_name">Subcolumn name</label>
                                <p>{{ update_subcolumn_form.name }}</p>
                                <br />
                                {% for error in update_subcolumn_form.is_border_column.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_is_border_column">Is border subcolumn?</label>
                                <p>{{ update_subcolumn_form.is_border_column}}</p>
                                <br />
                                {% for error in update_subcolumn_form.is_highest_priority_card_column.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_is_highest_priority_card_column">Is a highest priority subcolumn?</label>
                                <p>{{ update_subcolumn_form.is_highest_priority_card_column}}</p>
                                <br />
                                {% for error in update_subcolumn_form.is_acceptance_testing_column.errors %}
                                    <p style="float: right; color: red; font-weight: bold">{{ error }}</p>
                                {% endfor %}
                                <label for="id_is_acceptance_testing_column ">Is acceptance testing subcolumn?</label>
                                <p>{{ update_subcolumn_form.is_acceptance_testing_column }}</p>
                                <br />

                                <button class="btn btn-primary" type="submit">Update a subcolumn</button>
                            </form>

                            <br />

                            {% if is_update %}
                            <a href="{% url 'delete_subcolumn' subcolumn_id %}" class="btn btn-danger btn-large">
                                <i class="icon-white icon-remove"></i> Delete this subcolumn
                            </a>
                            {% endif %}

                        {% else %}
                            <h4 class="form-signin-heading">{{ message }}</h4>

                        {% endif %}

                    {% endif %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}